sudo: required
language: generic
services: docker

before_install: 
- docker image build -t dinkarinjosh/react-app-revise -f Dockerfile.dev .

script: 
- docker container run dinkarinjosh/react-app-revise -e CI=true npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react-revise
  env: Dockerreactrevise-env
  bucket: elasticbeanstalk-us-east-2-318587505622
  bucket_path: docker-react-revise
  on:
     branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY