version: "3"

services:
  my-react-app:
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-react-app-container
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules
      - ./:/app
volumes:
  node_modules:
